version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    command: npm run dev:server

  client:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: npm run dev:client
volumes:
  node_modules: