FROM node:16.13
RUN npm install -g webpack
WORKDIR /usr/src/app
COPY package*.json /usr/src/app/
RUN npm install
COPY . .

# Compile TypeScript files
RUN npm run build

EXPOSE 3001

# Start the server using the compiled JS files
CMD ["npm", "run", "dev:server"]